name: Python application

on:
  push:
    branches: [ "main" ]
    tags:
      - "**"
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write
  actions: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ${{ matrix.image }}
    strategy:
          fail-fast: false
          matrix:
            include:
              - image: ubuntu-24.04
                os: linux
                cpu: x64

              - image: windows-2022
                os: windows
                cpu: x64

              - image: macos-13
                os: macos
                cpu: x64

              - image: macos-14
                os: macos
                cpu: arm

    steps:
    - name: Checkout the code
      uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v5
      with:
          version: "0.7.19"

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version-file: "pyproject.toml"

    - name: Install the project
      run: uv sync --locked --all-extras --dev

    - name: Run tests
      run: uv run pytest

  deploy:
    if: startsWith(github.ref, 'refs/tags/')
    needs:
      - build
    runs-on: ubuntu-latest
    steps:
      - name: Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # pointless job that allows using a single check for PR dependencies
  build_post:
    name: Build Post
    needs: build
    runs-on: ubuntu-latest
    steps:
      - run: "true"